FROM node:22-alpine

WORKDIR /app

COPY package.json ./
COPY pnpm-lock.yaml ./

COPY ./apps/http-backend/package.json ./apps/http-backend/

RUN npm install -g pnpm

RUN pnpm install

COPY . .

RUN npm run db:generate

RUN npm run backend:build

EXPOSE 8080

CMD ["npm", "run", "backend:start"]
